spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: OnlineMovieService

logging:
  level:
    root: INFO
    com.github.onlinemovieservice: DEBUG
server:
  port: 8081